% -------------------------------------------------------------------
%  Generated by MATLAB on 9-Mar-2026 16:02:33
%  MATLAB version: 24.2.0.2923080 (R2024b) Update 6
% -------------------------------------------------------------------
      
load("sysid_motor_estim_final.mat");
tf_num = sys_tf.Numerator;
tf_den = sys_tf.Denominator;
Ts = sys_tf.Ts; % 0.02s -> 50Hz

throttle_offset = 0;

Gdc = dcgain(sys_tf);
motor_offset_rpm = Gdc * throttle_offset; 

air_bearing = struct;
air_bearing.damp_translation = 0.1;
air_bearing.bound_translation = 2;
air_bearing.damp_rotation = 1E-5;

rotation_noise = 0.000000001.*ones(3,1); % N*m
imu_noise = 0.0005.*ones(3,1);
hall_sens_noise = 0.000001*ones(4,1);
camera_noise = 0.000001*ones(4,1);

% use Satellite Body Frame coord system in Simulink
% measurements without motors + inertial disks (added separately in Simulink)
deathstar = struct;
deathstar.radius = 150.5;
deathstar.mass =  2914.38262; %1926.04; grams
deathstar.com = 1000*[-0.00038007 0.00383771 -0.00834355]; %[x y z]*1000 so in mmm


% inertia = Three-element vector with the [Ixx Iyy Izz] moments of inertia specified relative to a 
% frame with origin at the center of mass and axes parallel to the block reference frame. 
% The moments of inertia are the diagonal elements of the inertia tensor 
deathstar.inertia = [ 0.02950258 0.02979540 0.03600815]; % [Lxx Lyy Lzz] from solidworks kg*m^2
% Three-element vector with the [Iyz Izx Ixy] products of inertia specified relative to a frame with 
% origin at the center of mass and axes parallel to the block reference frame. 
% The products of inertia are the off-diagonal elements of the inertia tensor 
deathstar.inertia_prod = [0.00190852 -0.00207035 -0.00186691]; %[Lyz Lxz Lxy] from solidworks kg*m^2

%translations defined from satellite frame to sensor frame
imu = struct;
imu.translation = [7.02797 0 -37.90000];%mm ;y should be approx 0
% rotation: z is the same, x=-x, y=-y

camera = struct;
camera.translation = [132.038 0 -11.128]; %mm ;y should be approx 0
camera.rotation = [0 -0 0]; %degrees; using x-y-z sequence %updated on physical setup o pe direcly in x axis
camera.beamdlength = 1500;%mm
camera.beamdradius = 2;%mm

laser = struct;
laser.translation = [128.531 0 8.761]; %mm ;y should be approx 0
laser.rotation = [0 -0 0]; %degrees; using x-y-z sequence
laser.beamdlength = 1500;%mm
laser.beamdradius = 2;%mm

%%
gravity = 0;
noise = 0;

%% inner loop - wheels
Kff = 1/14.01;
Kp = 0;
Ki = 0.1;

%%
% format long g
% I_total = out.inertia.Data(:,:,1)

I_total =[
        0.0325938780796586      -0.00192528711213483      -0.00214221992111931;
      -0.00192528711213483        0.0314521408239867       0.00200183889657857;
      -0.00214221992111931       0.00200183889657857        0.0375049296630568];

%% PID param - simple (throttle output, like on physical setup)
    % on the setup I was using a attitude error in degrees
    % for small angles quaternion error should be approximatly proportional
    % to angle q_e_i = 2 * theta_i (rads)
k_deg = 2*(180/pi);

kp_pitch = k_deg * 5;
ki_pitch = k_deg * 0.01;
kd_pitch = k_deg * 0.01;

kp_yaw = k_deg * 5;
ki_yaw = k_deg * 0.01;
kd_yaw = k_deg * 0.02;

%% PID param - paper: Sanfedino et al. - 2023

% wr = 2*pi*5; %bandwidth
% xi = 0.7;
% 
% Jxx = I_total(1,1);
% Jyy = I_total(2,2);
% Jzz = I_total(3,3);
% 
% wr_roll = wr;
% wr_pitch = wr;
% wr_yaw = wr;
% 
% % absolute performance error (rad)
% APE_roll  = deg2rad(0.3);
% APE_pitch = deg2rad(0.3);
% APE_yaw   = deg2rad(0.3);
% 
% % orbital disturbance (torque N*m)
%     % gravitational torque
% mass = 3.1; %kg
% theta = 20; %degrees
% r =  max(abs(deathstar.com))/1000; %pivot in m
% T_g = abs(gravity) * mass * r * sin(theta*pi/180);
% 
% T_ext = [T_g, T_g, T_g];
% % T_ext = rotation_noise;
% 
% Text_roll  = T_ext(1);
% Text_pitch = T_ext(2);
% Text_yaw   = T_ext(3);
% 
% wr_roll  = sqrt(Text_roll  / (Jxx*APE_roll));
% wr_pitch = sqrt(Text_pitch / (Jyy*APE_pitch));
% wr_yaw   = sqrt(Text_yaw   / (Jzz*APE_yaw));
% 
% w_roll = 20*wr_roll;
% w_pitch = 20*wr_pitch;
% w_yaw = 20*wr_yaw;
% 
% kp_roll  = Jxx*wr_roll^2;
% kd_roll  = 2*xi*Jxx*wr_roll;
% 
% kp_pitch = Jyy*wr_pitch^2;
% kd_pitch = 2*xi*Jyy*wr_pitch;
% 
% kp_yaw   = Jzz*wr_yaw^2;
% kd_yaw   = 2*xi*Jzz*wr_yaw;
% 
% ki_roll  = 0;
% ki_pitch = 0;
% ki_yaw   = 0;

%% other params
%%

pitch_rigid = struct;
pitch_rigid.offset = [-4.7 -98.4979 0];%mm

yaw_rigid = struct;
yaw_rigid.offset = [-4.7 0 -98.4979];%mm

smiData = struct;
smiData.RigidTransform = struct;

smiData.RigidTransform(1).translation = [];
smiData.RigidTransform(1).angle = [];
smiData.RigidTransform(1).axis = [];
smiData.RigidTransform(1).ID = [];

smiData.RigidTransform(2).translation = [0 -44.4 0];%[0 -44.199999999999989 0];
smiData.RigidTransform(2).angle = 0;
smiData.RigidTransform(2).axis = [0 0 0];
smiData.RigidTransform(2).ID = ['F[A2012XL_motor_rotating-1:-:Inertial_' 'disk-1]'];
smiData.RigidTransform(2).ID = convertCharsToStrings(smiData.RigidTransform(2).ID);

smiData.RigidTransform(3).translation = [4.7499656472990894 -4.8754349117542848 25.437573148263283];
smiData.RigidTransform(3).angle = 0;
smiData.RigidTransform(3).axis = [0 0 0];
smiData.RigidTransform(3).ID = 'RootGround[A2012XL_motor_rotating-1]';
smiData.RigidTransform(3).ID = convertCharsToStrings(smiData.RigidTransform(3).ID);
smiData.Solid = struct;

% again: moments of inertia specified relative to a frame 
% with origin at the center of mass !!!
% and axes parallel to the block reference frame

smiData.Solid(1).mass = 0.065; %kg
smiData.Solid(1).CoM = [0 5.5248028598464938 0];%mm
smiData.Solid(1).MoI = [10.428244005836939 18.783946680159808 10.428244005836946];%kg*mm^2
smiData.Solid(1).PoI = [0 0 0];%kg*mm^2
smiData.Solid(1).color = [0.83137254901960778 0.6705882352941176 0.12941176470588234];
smiData.Solid(1).opacity = 1;
smiData.Solid(1).ID = 'Inertial_disk*:*Default';
smiData.Solid(1).ID = convertCharsToStrings(smiData.Solid(1).ID);

smiData.Solid(2).mass = 0.06533406;
smiData.Solid(2).CoM = [0 14.047636536892741 0];
smiData.Solid(2).MoI = [8.0421883213430334 6.1481063317001245 8.042188321343037];
smiData.Solid(2).PoI = [0 0 0];
smiData.Solid(2).color = [1 1 1];
smiData.Solid(2).opacity = 1;
smiData.Solid(2).ID = 'A2012XL_motor_rotating*:*Default';
smiData.Solid(2).ID = convertCharsToStrings(smiData.Solid(2).ID);

J_motor = (smiData.Solid(1).MoI(2) + smiData.Solid(2).MoI(2))*(1e-6);%kg*m^2 
Init_cond_motor_angular_rate_rpm = 50/Kff * 60/(2*pi);
